CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(32),
    lastName VARCHAR(32),
    email VARCHAR(64) NOT NULL,
    hash VARCHAR(255) NOT NULL,
  	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    refreshToken VARCHAR(250),
  	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


alter table tokens add column expiredIn TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE EVENT expireToken
ON SCHEDULE EVERY 1 MINUTE
DO
DELETE FROM tokens
WHERE TIMESTAMPDIFF(DAY, expiredIn, NOW()) > 30
;